const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const email = "Email";
const emailhint = "admin@admin.com";
const password = "Password";
const passwordhint = "******";
const retypepassword = "Retype Password";
const name = "Name";
const namehint = "John Doe";
const forgetpass = "Forget Password";
const logout = "Log Out";
const login = "Login";
const Signup = "Sign Up";
const createnewaccount = "or, create new account";
const loginwith = "Log in with";
const privacy = "Privacy Policy";
const term = "Terms and Conditions";
const alreadyhaveaccount = "Already have an account?";
const home = "Home";
const Category = "Categories";
const cart = "Cart";
const account = "Account";
const searchanything = "Search anything...";
const todaydeal = "Today's Deal";
const flashsale = "Flash Sale";
const topseller = "Top Sellers";
const brand = "Brands";
const topcategories = "Top Categories";
const featuredcategories = "Featured Categories";
const womendress = "Women's Dresses";
const girlswatches = "Girls Watches";
const mobilephone = "Mobile Phones";
const boysglasses = "Boys Glasses";
const tshirts = "T-Shirts";
const girldress = "Girls Dresses";
const featuredproduct = "Featured Product";
const womenclothing = "Women Clothing";
const menclothing = "Men Clothing";
const compAcc = "Computer & Accessories";
const automobile = "Automobile";
const kidtoys = "Kids & Toys";
const sports = "Sports";
const jewellery = "Jewellery";
const cellphone = "Cell Phones & Accessories";
const furniture = "Furniture";

const video = "Video",
    reviews = "Reviews",
    sellerpolicy = "Seller Policy",
    returnpolicy = "Return Policy",
    supportpolicy = "Support Policy",
    productyoumaylike = "Products you may like";

const wishlist = "My Whislist", orders = "My Orders", messages = "My Messages";
